### PR TITLE
Add nlpsandbox.io badge

### LINKED ISSUE #88: Create badge that redirect to the Leaderboard page of this NLP Task
The badge could also be used in the Documentation on Synapse

- Badge icon: [Synapse logo](https://www.synapse.org/images/logo.svg)
- Badge label: "Leaderboard" or "Benchmark" or "Benchmarked on nlpsandbox.io" (maybe a bit long) or just "nlpsandbox.io"

### PR DESCRIPTION
**Pull request by tschaffter**
Fixes #88 

This badge will be simplified once we have added the Synapse logo to https://simpleicons.org/

### CODE REVIEW

**Comment by tschaffter** [comment]
The badge renders correctly in VS Code but not on GitHub:

image

**Comment by tschaffter** [comment]
@thomasyu888 This is the [page of the leaderboard of the Date Annotator](https://www.synapse.org/#!Synapse:syn22277124/wiki/608039) (staging; one table for now, maybe more in the future). It would be awesome if we could add a query parameter to the URL to filter the content of the table(s). Is it possible? Can the Synapse tables use a query parameter to filter their content?

**Comment by thomasyu888** [comment]
You unfortunately can't add to query parameters to the URL but you can definitely add to the query statement in the widget. Or... You can link out to a specific query from the submission view ( it's a pretty ugly and long link per query )

**Comment by tschaffter** [comment]
I opened a ticket on Jira to register the Synapse logo on https://simpleicons.org/:
https://sagebionetworks.jira.com/browse/SWC-5415

**Comment by tschaffter** [comment]
> You unfortunately can't add to query parameters to the URL but you can definitely add to the query statement in the widget. Or... You can link out to a specific query from the submission view ( it's a pretty ugly and long link per query )

This idea - which you probably understood - is to customize the URL of the badge so that when clicked, we navigate to the leaderboard page and see only the submission for the tool name "awesome-team" or made by the submitterId "xyz". A button on the page would allow to clear this filter.

If I understand correctly, there is no way on Synapse to customize the content of a table embeded in a page using query parameters, is that correct? But are you saying that it's possible if we redirect to a Synapse Table directly (i.e. not embeded in a wiki page)?

**Comment by thomasyu888** [comment]
So there are already dashboard pages that allow submitters to see their own submissions.  This is done by adding to the SQL query and displaying it on the leaderboard.

You are correct when you say that there is no way of customizing the contents of table embedded in a wiki page with URL OR the table itself.  To clarify, you cannot do this:

wiki page: Synapse.org/...syn123/wiki/1234?query=submitter=1111
Table: synapse.org/...syn1233?query=submitter=1111

You must do the query first in the table, then you will get a link. You can provide this link to people but it will always be that specific query.  Does this make sense? (Sorry am on my phone)

**Pull request merged**
